name: hail
dependencies:
  - python=2.7
  - Sphinx=1.5.4
  - conda-forge::nbsphinx=0.2.13
  - conda-forge::sphinx_rtd_theme=0.2.4
  - decorator=4.0.10
  - ipython-notebook=4.0.4
  - numpy=1.11.1
  - pandas=0.20.2
  - matplotlib=2.0.2
  - seaborn=0.7.1
